const traducciones = {
    español: {
        titulo: 'Configuracion de la aplicacion',
        prefe: 'Preferencias del Usuario',
        idioma: 'Idioma',
        seleccionaIdioma: 'Seleccione el idioma de la aplicación',
        tema: 'Tema',
        seleccionaTema: 'Selecciona el tema de la aplicación',
        tamañoFuente: 'Tamaño de Fuente',
        seleccionaFuente: 'Selecciona el tamaño de fuente',
        modoLectura: 'Modo Lectura',
        guardarCambios: 'Guardar Cambios',
        español: 'Español',
        ingles: 'Inglés',
        claro: 'Claro',
        oscuro: 'Oscuro',
        pequeña: 'Pequeña',
        mediana: 'Mediana',
        grande: 'Grande',
        modoLecturaActivo: 'Modo Lectura Activo',
    },
    ingles: {
        titulo: 'Application configuration',
        prefe: 'User Preferences',
        idioma: 'Language',
        seleccionaIdioma: 'Select the application language',
        tema: 'Theme',
        seleccionaTema: 'Select the application theme',
        tamañoFuente: 'Font Size',
        seleccionaFuente: 'Select the font size',
        modoLectura: 'Reading Mode',
        guardarCambios: 'Save Changes',
        español: 'Spanish',
        ingles: 'English',
        claro: 'Light',
        oscuro: 'Dark',
        pequeña: 'Small',
        mediana: 'Medium',
        grande: 'Large',
        modoLecturaActivo: 'Reading Mode Active',
    },
};

export default traducciones;